### ISSUE TITLE
Loading native libgtksourceview shared library failed

### ISSUE THREAD

**Issue by lamg** [gircore/gir.core#1082]
### Description
A basic example using `GtkSource` fails to run with the following output

```
UnhandledException - unhandled exception: System.DllNotFoundException: Unable to load shared library 'GtkSource' or
one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable
```

### Steps to reproduce
- copy to your local machine the project at https://github.com/lamg/exercises/tree/master/gtk_fsharp/gir_core/source
- execute `dotnet publish -c release` and then `bin/release/net8.0/source`

### Investigating the issue
- execute `export LD_DEBUG='libs bin/release/net8.0/source'`
- execute `bin/release/net8.0/source 2> result.txt`

### Inspecting the output at `result.txt`
- it shows the program is looking for `/usr/lib/x86_64-linux-gnu/libGtkSource.so`
- it should be looking for `libgtksourceview-5.so` instead

**Comment by badcel** [comment]
Actually it should be looking for `libgtksourceview-5.so.0` as it is [defined in the Gir file](https://github.com/gircore/gir-files/blob/c2dab7dee23d5b5aa29bfb43c9191412cef65f59/linux/GtkSource-5.gir#L14) from the GNOME sdk.

Can you confirm this file is available?

Which version of Ubuntu are you using?

**Comment by lamg** [comment]
I assumed wrongly it would be looking for `libgtksourceview-5.so`, nevertheless  `/usr/lib/x86_64-linux-gnu/libgtksourceview-5.so.0` exists in my system.

The above mentioned `result.txt` file in my machine shows [this line](https://github.com/lamg/exercises/blob/af34852564f31319756c02f7eb31b54cf6432fa4/gtk_fsharp/gir_core/source/result.txt#L916). To me this suggests there's something wrong with the way the path is determined.

**Comment by lamg** [comment]
Problem solved, forgot to call `﻿GtkSource.Module.Initialize()`, like the example shows [here](https://github.com/gircore/gir.core/blob/7545f0f4036f458c89ead15d36db255bfbfb2b91/src/Samples/GtkSource-5/GtkSourceView/Program.cs#L1). Thanks!
