### ISSUE TITLE
Skip code generation for repositories that were pulled in as includes

### ISSUE THREAD

**Issue by adamreeve** [gircore/gir.core#1084]
Continuing the discussion from https://github.com/gircore/gir.core/issues/1078#issuecomment-2187914806

Currently the GirTool generate command accepts a list of input repository files to generate code for. Any includes in these files are resolved and added to the list of output repositories by the `RepositoriesDependencyResolver` class. This is needed for generating code for interacting with dependencies, but sometimes users won't want to generate code for all dependencies but rather use them via package references, such as when using GirCore.GLib-2.0 for example.

I'd like to change the GirTool behaviour so that these includes that aren't from repositories explicitly listed in the `input` argument don't get code generated. They would still need to be loaded and resolved though.

**Comment by badcel** [comment]
This sounds like a good first step into the right direction for me. Fell free to work on this item :rocket: .
