### ISSUE TITLE
gint64 array length parameters cause invalid cast error

### ISSUE THREAD

**Issue by adamreeve** [gircore/gir.core#1098]
Since #1067 was merged, I now get errors building bindings for methods where the array length has type `gint64`. I've pushed a change to the GirTest library to reproduce the error here: https://github.com/adamreeve/gir.core/commit/f93b90f7ce31bde5302b5ee3a73dee88cb7b5f3a

The generated method looks like:
```c#
public static int GetDataWithGint64Size(Span<int> data)
{
    var resultGetDataWithGint64Size = GirTest.Internal.IntegerArrayTester.GetDataWithGint64Size(ref MemoryMarshal.GetReference(data), (long) data.Length);
    return resultGetDataWithGint64Size;
}
```

The expected type of the length parameter to the internal method is `CLong` rather than `long`, which causes errors when building the generated code like:
```
error CS1503: Argument 2: cannot convert from 'long' to 'System.Runtime.InteropServices.CLong'
```

This appears to be due to the `PrimitiveValueTypeArray` implementation of `ToNativeParameterConverter` here: https://github.com/gircore/gir.core/blob/7c1b5a8ada2b31bd69b9e5f0d27585d6e572627c/src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PrimitiveValueTypeArray.cs#L56

But I haven't yet figured out how best to fix this. I guess we want to reuse the `Long` instance of `ToNativeParameterConverter` rather than hard code the cast here?

**Comment by badcel** [comment]
Hey I did not yet take a detailed look at this bug but it can be that there is no easy fix for it and needs updating the typehandling of the generator.

[Gint64](https://docs.gtk.org/glib/types.html#gint64) is guaranteed to be 64 bits on all platforms.

The GirLoader [maps Gint64 to long](https://github.com/gircore/gir.core/blob/7c1b5a8ada2b31bd69b9e5f0d27585d6e572627c/src/Generation/GirLoader/TypeReferenceResolver/TypeReferenceResolver.GlobalTypeCache.cs#L62).

The `GirModel.Long` is currently mapped to [CLong](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.clong?view=net-8.0) in the internal APIs as the C long is only 32bit on windows and 64Bit on other platforms.

This is obviously wrong for GInt64 as it has 64Bit on all platforms. So either there must be a new Type like `Long64` or a property must be added to `Long` detailing whether it is always 64 bit or not.

I need to take a more detailed look here.

**Comment by badcel** [comment]
@adamreeve This should be fixed again. Thanks for reporting.

**Comment by adamreeve** [comment]
:+1: thanks for fixing this!
