### ISSUE TITLE
Support GStreamer (Gst Plugins)

### ISSUE THREAD

**Issue by firox263** [gircore/gir.core#112]
We should support using GStreamer with Plugins (as base GStreamer isn't all that useful). I think it's best we get this working ahead of any generator rewrite, since GStreamer uses GObject directly.

 - GStreamer plugins have individual gir metadata files (see [gstreamer-rs/gir-files](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/tree/master/gir-files)).
 - It would make sense to namespace plugins under `Gst`, for example `GstAudio` -> `Gst.Audio`.
   - I'm not sure if we can infer this from gir data?
 - Parts of GStreamer rely on [first-class interface support](https://gstreamer.freedesktop.org/documentation/application-development/advanced/interfaces.html?gi-language=c), so this will include #110 and #104.
 - Outside of Gtk, GStreamer is the other big client of GObject, so there'll be [intricacies](https://gstreamer.freedesktop.org/documentation/application-development/basics/elements.html?gi-language=c#using-an-element-as-a-gobject) to work around.
   - While typed properties (via property descriptors) are great and should be used whereever possible, GStreamer relies on being able to retrieve properties from string representations too.
 - Easy GStreamer <-> Gtk interop for writing media-enabled applications.

Considerations:
 - Investigate [controlled properties?](https://gstreamer.freedesktop.org/documentation/gstreamer/gstobject.html#controlled-properties)
 - Allow for access to public struct member data (in the case of [GstObject->flags](https://gstreamer.freedesktop.org/documentation/gstreamer/gstobject.html#members))
 - Fix clash in generator between capitalisation and reserved keywords (e.g. `null`->`@null`, whereas it should be `null`->`Null`, see `Gst.State`).

**Comment by badcel** [comment]
Ah I forgot about the plugins. You are probably right, we should have some working samples before rewriting the generator (#100).
