### ISSUE TITLE
Troubles adding gresources to app

### ISSUE THREAD

**Issue by SpikedPaladin** [gircore/gir.core#1129]
Im trying building Gir.Core app on windows with embedding gresources to it, but can't figure out how to do this. Is there any guide or template?

**Comment by SpikedPaladin** [comment]
I mean embedding gresources.xml file with styles.css and other files in it

**Comment by badcel** [comment]
I think you want to do the things described [here](https://docs.gtk.org/gio/struct.Resource.html)? If you are into Vala programming you should probably be more into this topic than me.

I understand from the docs that there is `glib-compile-resources` binary which allows to create some binary file from an xml file and it's associated data. This is independent from dotnet and should already be useable via [g_resource_load](https://docs.gtk.org/gio/type_func.Resource.load.html) which is bound inside the [Resource](https://gircore.github.io/api/Gio.Resource.html) class.

The docs state that it is more common to embed the ressources into the executeable, what is not possible afaik, as there are no header files for dotnet and so on: 

>You can then use [glib-compile-resources](https://docs.gtk.org/gio/glib-compile-resources.html) to compile the XML to a binary bundle that you can load with [g_resource_load()](https://docs.gtk.org/gio/type_func.Resource.load.html). However, it’s more common to use the --generate-source and --generate-header arguments to create a source file and header to link directly into your application. This will generate get_resource(), register_resource() and unregister_resource() functions, prefixed by the --c-name argument passed to [glib-compile-resources](https://docs.gtk.org/gio/glib-compile-resources.html).

If you want to embed resources into the executeable, please refer to the sample mentioned in my previous comment. For separate resource binary it should work. If you care to contribute a sample it is very welcome. If it is not working please open a bug report.
