### ISSUE TITLE
Gracefully handle exceptions in the Build Tool

### ISSUE THREAD

**Issue by mjakeman** [gircore/gir.core#135]
Currently, if the build tool fails for whatever reason, it prints out the exception followed by a long stack trace. We should handle common failures gracefully and print out a helpful error message rather than >50 lines of stderr.

Particularly:
 * GIR files cannot be found -> Instruct the user to pull the most up to date version of gir-files (and/or init submodules)
 * Generation failure -> Print relevant inner exceptions only, rather than all of the threading-related exceptions Bullseye generates on failure. Could direct the user here to open an issue.

**Comment by sonicbhoc** [comment]
I'll take a crack at this.

**Comment by mjakeman** [comment]
Hey, thanks!

We're currently in the middle of a rewrite of the generator (which includes some big changes to the build tool), so it'd be great if you could base your changes on the branch [`generator-v2-typeintegration-methods`](https://github.com/gircore/gir.core/tree/feature/generator-v2-typeintegration-methods).

The main relevant project would be [`Build`](https://github.com/gircore/gir.core/tree/feature/generator-v2-typeintegration-methods/Build) and we do logging through a thin wrapper around Serilog defined in [`Log.cs`](https://github.com/gircore/gir.core/blob/feature/generator-v2-typeintegration-methods/Build/Log.cs).

Come join us on [Matrix](https://matrix.to/#/#gircore:matrix.org?via=matrix.org) if you have any questions :)

**Comment by mjakeman** [comment]
Some ideas from matrix:

> **firox263:** We're still lacking actual error messages (it blows up if you don't initialise submodules, and doesn't really tell you what the problem is)

> **badcel:** how would you detect that error regarding not initialized gir-files folder

> **firox263:** I think it's more a case of "Is the exception a file not found exception?" -> "Print something relevant and suggest checking that the gir-files folder exists and was cloned correctly"
> **firox263:** And do something similar for some other common exceptions

**Comment by badcel** [comment]
Just a quick idea: We probably should add some setting to the project which let's the user decide wether any errors are fatal or not.

As we are going to be the root of the C# GObject stack we probably want our CI to fail if there are any erros or methods missing or similar.

In case of a 3rd party dev where some parts of the gir are incomplete the user should probably be able to decide if any errors should be fatal or not. If errors should not be fatal our tree shaking would try to create a working API even if there are some errors.

**Comment by badcel** [comment]
> badcel: ah it could just be the same as the tree shaking
> so it could be quite easy
> if something is not resolved -> exception or not
> depending on a setting

> firox263:
> My idea is make a queue and push errors to it. At the end of validation, if queue length != 0 and -Werror, throw an exception

> Badcel
> or better: Why a queue?

> firox263
> I'm using the word 'queue' pretty broadly here. Basically a place to asynchronously dump errors until validation is over

**Comment by sonicbhoc** [comment]
Is there any reason to asynchronously dump errors if this isn't even running asynchronously? (For that matter, would it be worth switching to running asynchronously?)

**Comment by badcel** [comment]
The Generator part ist writing asynchronously to Disk [See Here](https://github.com/gircore/gir.core/blob/e5639157b682861a6ed3d776ea1517bc759ef804/Generator/Generator.cs#L41).

**Comment by badcel** [comment]
Please be aware that we merged all the new code into develop branch.

If you started your work already it is not a problem. It should be straight forward to rebase on develop if you are finished.

**Comment by sonicbhoc** [comment]
Sorry I haven't made progress on this. I will take time to work on it tonight.

> In case of a 3rd party dev where some parts of the gir are incomplete the user should probably be able to decide if any errors should be fatal or not. If errors should not be fatal our tree shaking would try to create a working API even if there are some errors.

In my mind, I see the user choosing which parts of the GIR they want and the generation bombing if those parts are not generated, which would also allow the user to skip generation of things they don't want. Since it's only building what the user wants (and its dependencies), any module failing to build would be world-ending.

Does this sound like a reasonable way to handle this?

**Comment by badcel** [comment]
We currently don't want any complex configuration of the generator. We can add it later if there is any demand. So I think a simple bool toggle wether an error is fatal or not is okay. Alternatively we would treat all errors as fatal for now.

**Comment by sonicbhoc** [comment]
> We currently don't want any complex configuration of the generator. We can add it later if there is any demand.

That's fair. In that case...

> Alternatively we would treat all errors as fatal for now.

This would be the best option IMO. Determining which errors are fatal and which aren't would require us to first know what our possible list of errors are and determine their severities.

**Comment by badcel** [comment]
Yep if you like your can come up with some creative ideas.

One idea would be to use the logger. The loggers could Store the highest severity they logged in the whole process of the repository/ generator. The build project read this values and if an error occured changes the final integer return value of the main method to 0/1 depending on the highest severity.

In this way the generator always tries to generate as much as possible and the decision if the generation was successful is made at the very end. This allows for easy reclassification of errors, too.

**Comment by badcel** [comment]
Fixed with #100
