### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by archanox** [gircore/gir.core#155]
It would be awesome to have a nuget package bundled up.

I'm keen to find a start creating c# apps for the Linux desktop/mobile software ecosystem, and I think this would go a long way.

**Comment by badcel** [comment]
We probably could build some alpha packages if we have #154 merged to get some early user feedback like crash reports.

But those packages would be far from complete, nor crash free, nor without memory leaks.

So I wonder if this would result in some bad reputation which I would like to avoid.

Perhaps it is acceptable for alpha users just to clone the repository and build yourself? As even the build pipeline is pure C# it is super easy to do.

What do you think?

**Comment by firox263** [comment]
@badcel I see you've beat me to it :smile:

I'm thinking we could add alpha nuget package generation as part of the CI pipeline (maybe relevant: https://devblogs.microsoft.com/devops/versioning-nuget-packages-cd-1/), and host these on GitHub (as opposed to NuGet), with a disclaimer that they shouldn't be used for anything serious. I'd like to fix #82 and #119 first however, so the packages are at least usable.

---

@archanox Great idea, and definitely something on the roadmap.

At the moment, we're heavily iterating on the bits which interact with GObject, so most changes are breaking (and another big change coming with #127). The bindings are not production ready, so I wouldn't use this for anything serious, but if you'd like to play around with it, I'd recommend using gir.core as a submodule in the mean time (see [here](https://github.com/firox263/Hyena/tree/master/ext) for some inspiration).

**Comment by badcel** [comment]
@firox263 I think you are right. If we want some pre release packages we should at least have fixed the most important point you mentioned.

What benefit do we have if we host the packages on github? How would the users be able to get those packages? For nugets we could add a [pre-release suffix](https://docs.microsoft.com/de-de/nuget/concepts/package-versioning#pre-release-versions).

**Comment by firox263** [comment]
Taken from that article I linked, they're not too keen on us releasing CI builds on nuget:

> Clarification [added May 5]: NuGet.org is not a good place to point your CI builds directly. It’s only for package versions you’re ready to release to the world. That’s what the previous paragraph intended to say, but it’s a little ambiguous.

GitHub Packages looked good, but it apparently [doesn't support non-authenticated downloads](https://github.community/t/download-from-github-package-registry-without-authentication/14407) for some reason, which makes it out of the question. We might end up using nuget after all, but I'd like to only have proper "releases" there.

**Comment by badcel** [comment]
I'm currently not for or against releasing pre releases on nuget.org but it makes the process for the user very easy. I think there are a lot of projects doing it e.g. the roslyn project: https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/

I'm not sure but I just changed CI to not use azure anymore. But it looks like azure is providing public nuget feeds.

**Comment by archanox** [comment]
> Taken from that article I linked, they're not too keen on us releasing CI builds on nuget:
> 
> 
> 
> > Clarification [added May 5]: NuGet.org is not a good place to point your CI builds directly. It’s only for package versions you’re ready to release to the world. That’s what the previous paragraph intended to say, but it’s a little ambiguous.

I think if you just enable NuGet publishing from tagged releases, it should be fine.

**Comment by badcel** [comment]
@archanox We are now technically prepared for doing nuget (pre-)releases. In #134 there is still some package renaming to be clarified and like mentioned above we have still some critical bugs.  

But as soon as we have s.th. useable we can go forward with some preview releases. Stay tuned!

**Comment by badcel** [comment]
If the nuget packaging lands after #436 it need to take platform specific gir-files into account.

**Comment by badcel** [comment]
It should be clear from a nuget package against which version of a gobject library it is build.

**Comment by badcel** [comment]
To get things started we can try to publish a MyGet feed intended for developers only.

**Comment by badcel** [comment]
With https://github.com/gircore/gir.core/pull/658 merged there are initial pre release nuget packages available under https://www.nuget.org/profiles/GirCore
