### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by mmaguigan** [gircore/gir.core#23]
@badcel, I am very intrigued by this project and it's goals. I too would like to see libhandy brought to .NET to help bring .NET Core to mobile devices (eg. smartphones) and responsive interfaces on desktops.

I saw your open invitation for contributors on issue 144 of GtkSharp and examined the projects current progress and have to say this is a very exciting project.

Is there an area where you would prefer to see contributions in this endeavor?

**Comment by badcel** [comment]
Yeah I'm interested in your opinion. What do you think of the current API design in general? I'm interested especially in the "Property"-Interface which allows to subscribe to property changed events per property.

The next step would probably to write more bindings, which should be quite easy.

I'm currently working on the new version of the generator which I should be ready soon.

**Comment by badcel** [comment]
The issues tagged with the "enhancement" are work items everybody can work on. Just assign yourself to an issue so everybody knows you are working on it and the work is not happening twice.

The issues tagged with "good first issue" should be easy and straight forward to do.
