### ISSUE TITLE
Add LibAdwaita

### ISSUE THREAD

**Issue by gavr123456789** [gircore/gir.core#375]
LibAdwaita is like LibHandy for GTK 4, but its purpose has changed, if earlier LibHandy was to simplify the development of mobile interfaces, now it is a more general library whose purpose is to facilitate the development of GTK 4 applications by providing ready-made implementations of HIG patterns. It seems that all new GTK applications use it.  
  
https://adrienplazas.com/blog/2021/03/31/introducing-libadwaita.html

**Comment by iMonZ** [comment]
Best thing is to drop the plan for libHandy and replace it with LibAdwaita it would make much more sense

**Comment by badcel** [comment]
Libadwaita gir file is now available on the develop branch. 

To get libadwaita into the develop branch the following things must be done:

- [ ] Creating the C# project
- [ ] Add a sample showcasing libadwaita widgets

This is a good starting point for new contributors.
