### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by firox263** [gircore/gir.core#38]
Ideally, gir.core should be able to work 'out of the box' on Windows.

**Building**
I've managed to get the project building (see #37). This involves remapping shared library names to dll names in order to link with the proper libraries.

**GTK Binaries**
GTK Binaries must be installed manually at the moment. I am using the MSYS2 binaries since they are the recommended way to get GTK on Windows (from the [website](https://www.gtk.org/docs/installations/windows/)). 

To link with the native libraries, I added a function that remaps the shared library name to the DLL name. This is problematic as MSYS2 and vcpkg use different DLL names (`libglib-2-0.dll` vs `glib-2.dll`). It looks like vcpkg might be updating their GTK builds to use meson directly, so hopefully this will be fixed.

**Missing Libraries**
There are a few other issues remaining, most notably that webkit2gtk doesn't build on Windows anymore (see PR for info). We might need some way of marking a lib as platform specific, so we don't unnecessarily generate wrappers.

Feedback is very much appreciated.

**Comment by badcel** [comment]
I think as long as there is no release we can create a Windows version if it is compiled under Windows.

If there is a first release we should somehow create a platform independent version of the libraries.

A possible way is using the new .net core APIs: https://developers.redhat.com/blog/2019/09/06/interacting-with-native-libraries-in-net-core-3-0/

In general I like the msys2 approach as we don't need to distribute the packages for Windows. If there are packages missing it would work automatically work if the packages are created.

**Comment by firox263** [comment]
Yeah, I agree.

At the moment it's probably fine to generate a Windows-specific version, but once we push for a major (or beta/usable) release, it might be better to use the new .NET apis to lookup the library in a cross-platform way. It would also solve the DLL name dilemma as we could prioritise `libglib-2-0.dll` and then lookup `glib-2.dll` as a fallback.

**Comment by firox263** [comment]
A quick update on actually building the libraries. Cairo has just landed a [meson port](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/37), which means the entire GTK Stack should now be buildable with Meson. Previously, cairo used Autotools which was a nightmare to build with MSVC.

Hopefully this means it'll be much easier to get started with GTK (and by extension, gir.core) on Windows.

**Comment by firox263** [comment]
Finally managed to get to the bottom of an odd issue where OmniSharp thought it was running on linux and sometimes wouldn't give me Intellisense.

In [Directory.Build.props#L4](https://github.com/gircore/gir.core/blob/a15fe382b5cd0b237d6b4831ca21e202db3e7f4b/Libs/Directory.Build.props#L4) we explicitly set the Runtime Identifier to 'linux'. Is there any particular reason for this line, or could we safely remove it?

@badcel

**Comment by badcel** [comment]
I just tested it. We can safely remove it. The document states that it is used for self contained deployments. As we don't need this at the moment we are good to go without it. I'm going to create a pull request.

**Comment by firox263** [comment]
Closing this since we already have full support for building on Windows. Having a way for end-users to get Gir.Core without building it (or obtaining Gtk) themselves would be nice, but is probably for another issue.
