### ISSUE TITLE
Improve Text Editor Sample

### ISSUE THREAD

**Issue by mjakeman** [gircore/gir.core#398]
The text editor sample introduced by #323 is a good first iteration.

The piece table implementation could use some work (Support Deletion, Undo/Redo, Piece Merging).

We should also be using Pango for text layout rather than Cairo.

Some other possible additions:
- Drag and Drop
- Event Controllers
- GActions
- GSettings
- GTK 4? 

This would make it a nice starting point for GTK/C# beginners.

**Comment by badcel** [comment]
I don't mind keeping the text editor in this repository for now as it could help is debug problems in our generated code.

If you plan to improve it even more then it gets more than a sample: it gets more like a demo app or even more.

If it gets like a demo I think we should move it out of tree in a separate repository (either in this org or into your personal account, like you prefer). As it is not in scope of this repository anymore.

I would like to advertise projects which are done using GirCore on the homepage, this could be the  first but hopefully not the last project which is listed there. 🚀

**Comment by mjakeman** [comment]
Yeah, I don't want to make it too complex, otherwise it negates the point of being a sample. I'd say it's maybe ~80% complete at the moment.

I think there's some benefit to having a 'medium-size' sample in the repo. Mainly, I'm wanting to illustrate:
 - Custom Widget Creation
 - Custom Drawing
 - Input Handling
 - Integrating .NET and GTK (this is why it doesn't just use GtkTextBuffer)

And it doubles as a testsuite for us in keeping these things working.

As for improving it, the text editor demo in this repo is effectively a stripped down version of the [actual word processor](https://github.com/mjakeman/bluetype/tree/wip/mjake%2Fgenerator-compat) I've been working on from time-to-time, so I'm intentionally trying to keep our demo simple.

**Comment by badcel** [comment]
The text editor sample got removed as it was not ported to GTK 4 and was to complex for a sample project.
