### ISSUE TITLE
Platform specific gir files

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#436]
Todo:
- [x] Provide platform specific gir-files(https://github.com/gircore/gir-files/pull/9, https://github.com/gircore/gir-files/pull/8, https://github.com/gircore/gir-files/pull/7)

# Pull Request 1 
- [x] Add new interface `PlatformDependent` to GirModul with properties: SupportsLinux, SupportsMacos, SupportsWindows
- [x] Add new folder / namespace "Platform" to GirLoader.
- [ ] Proxy existing output classes in the "Platform" namespace and add interface `PlatformDependent` to them.
- [ ] Add new class "Namespace" into "Platform" namespace which can be initialized with different regular namespaces via methods like `setLinuxNamespace(Namespace ns)`. This class implements the `Namespace` interface itself and returns the proxy classes which contain additional platform dependent data.

# Pull Request 2  
- [ ] Add one general Renderer for `PlatformDependent` objects to `Generator3` project which returns the `SupportedOsPlatformAttribute`
- [ ] Let the generator model implement `PlatformDependent` interface and route the information from the GirModel if it implements `PlatformDependent`.

# Pull Request 3
- [ ] Add new command to gir tool which uses the new repository which supports multiple platforms.

-----
Gir files are platform specific. E.g. for GTK on windows there are other methods as it uses the windows backend and not X/Wayland.

.Net supports two attributes to mark platform specific code:
- https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-5.0
- https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute

If we can extract this information from the gir or by diffing two gir files we can add attributes to mark platform specific code.

Perhaps we can use the msys2 GitHub action to build GTK for windows and extract the gir file.

https://github.com/msys2/setup-msys2

**Comment by badcel** [comment]
Perhaps we can use fedora to build recent versions of our libraries?

Perhaps we can use docker and source rpms?

https://fedoramagazine.org/how-rpm-packages-are-made-the-source-rpm/

**Comment by badcel** [comment]
It looks like Gtk-es builds GTK for windows:

https://github.com/gtk-rs/gtk4-rs/blob/200d25e577727a1d61536533fcdaae8da3ee7d0f/.github/workflows/windows-msvc.yml#L1

**Comment by badcel** [comment]
Alternative idea for multi platform aware binary:

do not use attribute to annotate unsupported api but multi target project. Windows / macOS specific api would need to be compiled conditionally (#if) and different binaries packed together into a single nuget package. The matching binary is used during runtime automatically.

Implementation idea for GirLoader supporting multi platforming

Symbols like "class", "method",... get new properties for different operating system eg "SupportsLinux". The gir Loader works with different folders containing platform specific gir files. This must happen at the input stage or a new "platform" stage must be introduced in between input and output which collects the platform specific informations so that the generation of the output model can contain the supported platform information.

**Comment by badcel** [comment]
The build process differentiates between platforms e.g. https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/meson.build#L383

Homebrew provides a Gtk4 package including their gir files: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk4.rb

Try Github actions: `brew install gtk4`

grab files like /usr/local/share/gir-1.0/Gtk-4.0.gir

**Comment by badcel** [comment]
In the first step it should not be relevant which api works on which platform.

Just generate independent bindings per platform (effectively duplicating a lot of generated code). Sharing Code between platforms can be achieved later to decrease nuget size.

**Comment by badcel** [comment]
If we have one dll per platform the dllimport class can be removed as it is not necessary anymore to detect the operating system during runtime.

This affects Cairo, too as it has a manual dll import.

**Comment by archanox** [comment]
Would this work encompass supporting different architectures?

**Comment by badcel** [comment]
I assume that it already supports different architectures?

We invoke the native methods via a Library name and a function name. The resolving of this is probably done via calls of dotnet runtime into the operating system which finds the dll and corresponding entry point and returns it to the runtime which makes it in turn available to custom code.

**Comment by badcel** [comment]
It looks like nuget packages can't deploy different sets of APIs per platform in one package. Thus we can create one platform independent base package and let the platform specific parts parts be in platform specific nuget packages which depend on the base package.
