### ISSUE TITLE
Update libhandy

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#47]
[libhandy](https://gitlab.gnome.org/GNOME/libhandy) has released the first beta of the final API. The API is marked stable. 

Update libhandy to a version >= 0.90.0 as soon as it is available as a package.

**Comment by firox263** [comment]
Some news:

Looks like `libhandy` is in the process of becoming `libadwaita`, which will be a "GNOME HIG" library for Gtk4 (See https://gitlab.gnome.org/GNOME/libhandy/-/issues/356). The plan, from what I can tell, is to rename/fork libadwaita from libhandy after the 1.0 release and move to Gtk4 exclusively.

When the fork happens (still some time off), we should package the "final" version of libhandy for Gtk3 and then look into Gtk4 builds for `libadwaita` going forward.

**Comment by badcel** [comment]
Libhandy1 is available in fedora: https://src.fedoraproject.org/rpms/libhandy1

**Comment by badcel** [comment]
This is probably obsolete if we do #396.
