### ISSUE TITLE
Verify how to run system tests during CI

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#504]
If docker container allows to start a display we could run the system tests during CI.

**Comment by badcel** [comment]
Alternatively there could be a gobject based c test library which provides an api to test the gobject system in depth without the need of a display

**Comment by badcel** [comment]
UI-Shooter has a headless mode spawning a Weston instance without a display: https://gitlab.com/rmnvgr/uishooter

Perhaps we could do the same to execute GTK unit tests?

**Comment by badcel** [comment]
In regard to #764:

My first idea would be that this repository should not care about some C code. There could be a new repository inside the GirCore organization which contains the C-Test library.

The new repository could have some GitHub action to build the code for different platforms and host the binaries and gir files alongside the code.

This repo is included as a git subproject in GireCore/gir.core repository.

The binding for the new c library would be part of the GirCore solution but would not be published.

This allows us to move all tests over to the new library freeing us of the need to have GTK installed to execute the tests.

**Comment by cameronwhite** [comment]
Thanks! Yeah I think moving it to another repo makes sense
The binaries should be fairly small / not frequently updated so storing them in the repo should hopefully be fine
