### ISSUE TITLE
Support WebKitGTK once it supports GTK4

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#505]
Support WebKitGTK once it supports GTK4

Original sample with JavaScript integration: https://github.com/gircore/gir.core/blob/v0.0.1/Samples/Gtk3/GtkApp/MyWindow.cs

**Comment by mikkeljohnsen** [comment]
Could WebKitGTK for GTK3 not be wrapped also ?

Since both Gtk3 and Gtk4 is wrapped.

**Comment by badcel** [comment]
No it won’t be supported as GTK3 will be removed see #396.
