### ISSUE TITLE
Verify removing of declarative Ui

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#530]
Verify how much simpler the code would be without declarative Ui especially regarding signals and if it's work to keep it.

**Comment by badcel** [comment]
@na2axl could you make a statement on this topic again? I think declarative UI is not a huge benefit for us. Writing big applications is probably not a thing as everything would need to be in one file. And for small applications it adds little benefit.

The static property access itself also adds little benefit as we have no UI layer like WPF but only the UI files and composite templates.

Am I missing something? Otherwise I would tend to remove it to simplify the code.

**Comment by badcel** [comment]
Perhaps it is a bit more functional. But for F# there would probably be different static property accesssors e.g. the setter should probably return the instance to allow pipelining?

**Comment by na2axl** [comment]
Hey @badcel, it's been a while :-)

I think we had a discussion about it in #34, the goal was to fit in the C# UI ecosystem. But if it doesn't fit the current project architecture, I feel we can separate this part in an UI layer/project which depends on the wrapper layer/project.

**Comment by badcel** [comment]
Ah thanks for the hint of #34. I did still not look into reactive Ui. But from a quick glance it looks like binding could be done through expressions?

E.g. this is taken from reactive ui and Avalon is sample: this.BindCommand(ViewModel, viewmodel => viewmodel.ExampleCommand, view => view ExampleButton)
