### ISSUE TITLE
Verify if GhostPad should be sealed

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#533]
Verify if GhostPad class should be "sealed" / "final" as the constructors contain code which must be executed and a derived class uses the generic constructor which does not execute the custom code. 

It does not set the "final" gir attribute (#532). Is this an upstream bug?

[Our Code](https://github.com/gircore/gir.core/blob/f4520e12f2c8a64668254b8f5055d0398aafc7ac/src/Libs/Gst-1.0/Classes/GhostPad.cs)

[Upstream code](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gstreamer/gst/gstghostpad.c#L667)

Explanation from ebassi: https://www.bassi.io/articles/2021/07/27/final-types/

@firox263 As you did add the comment regarding the ghost pad constructor can you confirm this again as the code is pretty old? And if so: should the class be marked as final upstream or do we add the sealed attribute ourself or do we ignore this?

**Comment by mjakeman** [comment]
This is not so relevant now that we're generating "factory"-style constructors. Users who wish to use the GStreamer API directly will just use the constructor method. Subclasses would need to reimplement that logic anyway, so I think it's fine to leave it as-is.

Also, GstGhostPad is (afaik) meant to be derivable, so making it sealed would be an error.
