### ISSUE TITLE
Convert namespace names to PascalCase

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#577]
A couple gir files, such as cairo and xlib, specify a lower case namespace name (e.g. for cairo, `<namespace name="cairo" version="1.0" ...`). This becomes the actual namespace name in the generated code, e.g. `cairo.ImageSurface`, which is inconsistent with the other libraries and the usual C# naming conventions (`Cairo.ImageSurface`)

**Comment by badcel** [comment]
This is a good idea. With the new generator the needed infrastructure is already in place to do this.

The correct place for a new method which does the conversion to pascal case would be in the [NamespaceNameExtension](https://github.com/gircore/gir.core/blob/develop/src/Generation/Generator3/ModelExtension/NamespaceNameExtension.cs). 

To convert to pascal case compare the MemberNameExtension: https://github.com/gircore/gir.core/blob/62d8a7ba5039b3e9a43019f194b238f623ba6e44/src/Generation/Generator3/ModelExtension/MemberNameExtension.cs#L7

The last step would be to update all the models which access `namespace.Name` and replace the property  `Name` access with the new extension.
