### ISSUE TITLE
Verify if record constructor should only accept owned handles

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#584]
Currently the public constructor for records accepts any kind of handle.

There is already a constructor generated for `Surface` and all other records:

```CS
public Surface(Internal.SurfaceHandle handle)
{
    _handle = handle;
    Initialize();
}
```

The code just expects a handle base class. But in case the handle is unowned we create a record instance which is based on an unowned handle. This means the handle can vanish any time. But the lifetime of our dotnet instance must be linked to the instance.

This probably means that the constructor should only accept `OwnedSafeHandles`. It is the callers responsibility to provide the `OwnedSafeHandle`. This keeps code on this level clean and we do not have to fiddle around with reference counting.

The reference counting should be part of the safe handle classes. Perhaps an `UnownedSafeHandle` like `MyExampleUnownedHandle` can have a method like `public MyExampleOwnedHandle Own()` which would increment the reference count of the handle by one and return an owned handle.

I did a quick check for the surface class and the GTK 3 method `gtk_offscreen_window_get_surface` returns an unowned surface handle. As we want to return the surface to the caller of our generated method we need to own it beforehand. This requires a change in the `ReturnTypeConverter.ToManaged` file. It would need to call the new `Own` method in case the `Transfer` property of the `from` variable is `None`.

See: https://github.com/gircore/gir.core/blob/62d8a7ba5039b3e9a43019f194b238f623ba6e44/src/Generation/Generator3/Converter/ReturnTypeConverter.ToManaged.cs#L56

**Comment by cameronwhite** [comment]
Looking at this a bit, in many cases we could generate the `ToOwned()` method similar to how the `ReleaseHandle()` for an OwnedHandle is generated, e.g. look for a standard method to bump the reference count (e.g. `g_date_time_ref()`) or duplicate (`g_date_copy()`)

It seems like there are some cases, though, where we have a unowned handle that doesn't have any way to copy it
e.g. for `GLib.OptionParseFuncHandler` ([C docs](https://docs.gtk.org/glib/callback.OptionParseFunc.html)), the managed callback gets an `OptionContext` which is owned by the calling function and doesn't have a copy/ref method that I can see. So if the managed callback holds onto `contextNative` then it could have a dangling reference

```csharp
NativeCallback = (context, group, data) => {
    var contextNative = new GLib.OptionContext(new GLib.Internal.OptionContextUnownedHandle(context));
    var groupNative = new GLib.OptionGroup(new GLib.Internal.OptionGroupUnownedHandle(group));

    var managedCallbackResult = managedCallback(contextNative, groupNative, data);
    return managedCallbackResult;
};
```

**Comment by badcel** [comment]
Hm perhaps we leave it like it is then for now?

Currently the freeing of the safe handle is missing, too:

https://github.com/gircore/gir.core/blob/eb0c6276662e8c3a2477cd4a892eb699f685f8b3/src/Generation/Generator3/Generation/Record/PublicClass/PublicClassTemplate.cs#L44

In c there would be the same problem. If the pointer to an unowned reference is stored and accessed it could deliver invalid data I assume?

Perhaps we should just rename the issue and change it's direction into implementing the dispose method of records. During this change it must be verified how to handle instances of unowned handles.

**Comment by cameronwhite** [comment]
Yeah I agree with leaving it as-is for now and addressing it along with the IDisposable stuff 👍

**Comment by badcel** [comment]
Records accept owned handles only. See #622.
