### ISSUE TITLE
Cairo: Name TextExtents fields in PascalCase

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#591]
The fields of the TextExtents struct should probably be written in PascalCase.

See: https://github.com/gircore/gir.core/blob/dce298dff0b9fcd86c38391aa860cd4fdcfa536c/src/Libs/cairo-1.0/Records/TextExtents.cs#L8

@cameronwhite what do you think?

**Comment by cameronwhite** [comment]
Agreed, I think those should be PascalCase
