### ISSUE TITLE
Samples link in readme is broken

### ISSUE THREAD

**Issue by hhyyrylainen** [gircore/gir.core#645]
There is a sample link in the main readme file: https://github.com/gircore/gir.core/blob/develop/Samples/Gtk3/DeclarativeUi/Program.cs which should probably be https://github.com/gircore/gir.core/blob/develop/src/Samples/Gtk3/DeclarativeUi/Program.cs for it to work

**Comment by badcel** [comment]
Thank you fixed in c7175f61b6f8392d8172be96a68546d82405796d.
