### ISSUE TITLE
Negative values in enums use an incorrect unicode character as the minus sign

### ISSUE THREAD

**Issue by hhyyrylainen** [gircore/gir.core#648]
I don't know if this is my setup or the generator but the following lines in all files get reported as errors (I just cloned the repo today and ran the generation):
```c#
        Nothing = −1,
```
in fact all numbers with the minus sign in front of them seem to be reported like this. In my IDE that character looks exactly like the minus sign (`-`) but seems like here on Github the character actually looks distinct from the minus sign.

Using emacs I confirmed that the actual characters in the files are not the normal minus sign but a unicode character that looks the same:
![Kuvakaappaus - 2022-07-23 13-46-43](https://user-images.githubusercontent.com/3796411/180601973-496c39a6-4c9f-4fe8-8114-f321944580dd.png)

Here's what it looks like after I corrected the character:
![Kuvakaappaus - 2022-07-23 13-46-56](https://user-images.githubusercontent.com/3796411/180601975-65fd8873-dabb-4429-8e04-2c6d30aa32e5.png)

So it seems the generator writes out a "MINUS SIGN" character instead of a "HYPHEN-MINUS" like it should.

**Comment by hhyyrylainen** [comment]
Running like this:
```bash
LANG=en.UTF_8 dotnet fsi GenerateLibs.fsx
```
Makes things work so there's something that's caused by a different locale `LANG=fi_FI.UTF-8` in the formatting. I think invariant culture use or something needs to be added to all to string conversion calls to fix things

**Comment by badcel** [comment]
You get a compile time error?

**Comment by hhyyrylainen** [comment]
Oh right, sorry I forgot to copy the error message, this is what I get without that fix when building:
```
2>/home/hhyyrylainen/Projects/gir.core/src/Libs/GLib-2.0/Enums/UnicodeScript.Generated.cs(15,23): Error CS1525 : Invalid expression term ''
2>/home/hhyyrylainen/Projects/gir.core/src/Libs/GLib-2.0/Enums/UnicodeScript.Generated.cs(15,23): Error CS1056 : Unexpected character '−'
2>------- Finished building project: GLib-2.0. Succeeded: False. Errors: 2. Warnings: 0
```

**Comment by badcel** [comment]
Hm interesting. The `Value` is of type long if it gets placed into the string. Perhaps it must be formatted as decimal?

Can you test this: `=> $"{ member.Name } = { member.Value:D },";`

**Comment by hhyyrylainen** [comment]
That doesn't actually compile (`22>/home/hhyyrylainen/Projects/gir.core/src/Generation/Generator3/Renderer/Public/Member.cs(9,50): Error CS8088 : A format specifier may not contain trailing whitespace.`) but fixing the syntax error the result is the same, enum values end up being `InvalidCode = −1,` and being invalid syntax due to that `−` character.

**Comment by badcel** [comment]
It looks like your locale specifies a certain character as minus sign which gets output instead of the regular minus sign, correct?

If the invariant locale would be set during runtime globally it could negatively impact log messages (not respecting locale). On the other hand manually marking generated code as invariant over and over again is not good either.

Any suggestions?

**Comment by hhyyrylainen** [comment]
> It looks like your locale specifies a certain character as minus sign which gets output instead of the regular minus sign, correct?

That's my understanding.

> Any suggestions?

I opened a PR with my one change that makes this project build fine on my system: https://github.com/gircore/gir.core/pull/649
