### ISSUE TITLE
CssProvider LoadFromData missing from non-internal generated class

### ISSUE THREAD

**Issue by hhyyrylainen** [gircore/gir.core#650]
It looks like I need to call it like this:
```c#
Gtk.Internal.CssProvider.LoadFromData(CssProvider.Handle, data, data.Length);
```

Instead of like the other load from variants:
```c#
CssProvider.LoadFromData(data, data.Length);
```

So looks like that one method is missing from the non internal CssProvider for some reason.

**Comment by badcel** [comment]
This is handled in #765.
