### ISSUE TITLE
[InvalidCastException] Thrown when accessing file of filechoosernative

### ISSUE THREAD

**Issue by nlogozzo** [gircore/gir.core#702]
I'm trying to open a folder with a `FileChooserNative` object as such:
```csharp
var openFolderDialog = Gtk.FileChooserNative.New("Open Folder", this, Gtk.FileChooserAction.SelectFolder, "Open", "Cancel");
openFolderDialog.SetModal(true);
openFolderDialog.OnResponse += (sender, e) =>
{
    if (e.ResponseId == (int)Gtk.ResponseType.Accept)
    {
        _controller.OpenFolder(openFolderDialog.GetFile().GetPath() ?? "");
    }
};
openFolderDialog.Show();
```
The dialog opens fine, however as soon as I accept the dialog, I get an `InvalidCastException` on this line: ` _controller.OpenFolder(openFolderDialog.GetFile().GetPath() ?? "");`
![image](https://user-images.githubusercontent.com/17648453/205716108-287e553b-bbd7-45a7-be8b-fe2d9f939996.png)

**Comment by badcel** [comment]
I think here is something fundamental missing in my code. The returned handle should be casted into an object which implements Gio.File but there is no such class available.
