### ISSUE TITLE
Gio.SimpleAction.Enabled property is not writable 

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#740]
This is a regression I noticed in version 0.2 (it was a `get / set` property in 0.1), but it has an easy workaround of using the `SetEnabled()` method

From a quick look this might be related to interface properties. `Gio.Action` has a [read-only 'enabled' property](https://docs.gtk.org/gio/property.Action.enabled.html), but `Gio.SimpleAction` also defines a [setter](https://docs.gtk.org/gio/property.SimpleAction.enabled.html) which seems to be skipped now

**Comment by badcel** [comment]
Yes if there is a property with the same name on the interface the interface property is preferred over the class one.

Any idea on how to fix this?

**Comment by cameronwhite** [comment]
In this case the gir file contains this for Gio.Action
```
      <property name="enabled"
                version="2.28"
                transfer-ownership="none"
                getter="get_enabled">
```
and this for Gio.SimpleAction
```
      <property name="enabled"
                version="2.28"
                writable="1"
                transfer-ownership="none"
                setter="set_enabled">
```

so in terms of what the gir file describes, Gio.SimpleAction isn't hiding / redefining the getter of the property and is just adding a setter, so "merging" the properties might be possible

**Comment by badcel** [comment]
As far as i know for methods there could be different implementations for methods with the same signature and name as those are just wired up to some target: https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gsimpleaction.c#L352

For properties you are probably right. The documentation states that there must be a "compatible property": https://docs.gtk.org/gobject/type_func.Object.interface_install_property.html

It looks like there are 2 usecases: Either a class overrides the interface property (`g_object_class_override_property()`) or installs a new property (like `Gio.SimpleAction` does) to be able to alter the property.

Currently if a conflict between an interface and class property is found the class property is disabled. To get this working I would not deactivate the interface method / property but mark it as: "ImplementExplicitly"

This would allow to still keep the separation between "normal" class properties and interface properties in the generator and should work without to much trouble.

I currently don't have a good idea on how to make it work with merging interface and class properties as the merging would be quite complex. E.G. where would be the merged property be stored? Do you have an elegant solution in mind? Do you think implementing it via explicit implementations (in case there is a conflict) would not solve the problem?

**Comment by cameronwhite** [comment]
I think your idea of making it an explicit implementation sounds good to me 👍
