### ISSUE TITLE
Verify if Typedictioanry is needed

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#77]
Verify if we really need the type dictionary. There was already an attempt to omit it: 34f0358b3d5f9ad8ce1ba83ec7ead23b0c845162

**Comment by na2axl** [comment]
Hi @badcel, is the type dictionary not only needed on the generator side ? To fix the issue @firox263 got when tried to generate `SignalArgs` implementations for example...

**Comment by badcel** [comment]
The Type dictionary is used at runtime to save the mapping between a System.Type and a GType.

Perhaps @firox263 remembers the problems, I can't remember or find the concrete reason we added it again. 

So I added this as a reminder. If the things are working (including virtual function support, etc.) we can check if it is really needed.

**Comment by firox263** [comment]
We need the type dictionary for our methods. When we receive a pointer from C, we need a way to map from an arbitrary GType to the corresponding C# class.

I think the runtime type dict is a necessary evil, but we definitely make it more performant now that we're generating everything

**Comment by badcel** [comment]
@firox263 can you give an example?

My current assumption is based on for example the dbus connection class: https://github.com/gircore/gir.core/blob/8115212a2a7a609dda705d97f040bca2ab62719d/Libs/Gio/Classes/DBusConnection.cs#L15

It gets an arbitrary pointer, it checks if this pointer is already known and if not it creates a new dbus connection. Afterwards the pointer is known.

In case of dbus the type dict would not contain an entry for the dbus connection because it is not registered from the beginning.

**Comment by firox263** [comment]
The main reasoning for having the type dictionary was to support upcasting and downcasting, as well as the [*is*](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is) keyword in conjunction with inheritance. If we have a widget, and we call [`gtk_widget_get_toplevel`](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-toplevel), we are returned a Gtk.Widget.

However, a plain widget isn't very useful and the user will likely want this as a window. For example, if it is a Gtk.ApplicationWindow, the user could downcast it as follows:

```cs
var appWindow = (ApplicationWindow)widget.GetToplevel();
```

That same window could be represented (upcast) as a regular Gtk.Window:

```cs
var window = (Window)appWindow;
```

Or perhaps both:

```cs
if (window is ApplicationWindow appWin)
{
    // Do some logic only for Application Windows
    appWin.ShowMenubar = true;
}

// Shared logic for both Window and AppWindow
window.Title = "Hello!";
```

In order for that cast to work, we can't just return a Gtk.Widget from the function 'GetToplevel()', but rather we need to return the real type of the gobject upcasted as a Gtk.Widget. In order for this to happen, we need to be able to determine the C# class which corresponds to the "Real Type" of the GObject at runtime, and then return a casted version of that to the user (this is a quirk introduced by many gtk functions return a generic base type or interface).

With our generator, I think we can have some kind of registration at startup of all types, avoiding the nasty recursive assembly search, however I'm not sure the type dictionary itself is avoidable.

**Comment by badcel** [comment]
The type dictionary is needed for the reasons mentioned above.
