### ISSUE TITLE
PixbufAnimation does not have constructors

### ISSUE THREAD

**Issue by fleimeris** [gircore/gir.core#771]
I've been playing with Pixbuf library and I noticed that PixbufAnimation does not have any constructor methods in public API (ex. `gdk_pixbuf_animation_new_from_file`). I would like to contribute to create them, is it okay in current stage of this project to add them ?

**Comment by badcel** [comment]
I think this will be fixed with #756 which is scheduled for version 0.4.0.

If you would like to contribute I would suggest #736 as a next step as #756 involves substantial changes in several layers of the project.

**Comment by cameronwhite** [comment]
This is fixed now with #756
