### ISSUE TITLE
Ownership transfer issues for methods like gtk_widget_add_controller()

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#783]
I ran into some mysterious errors in Pinta related to event controllers, and think I have it tracked down. 

The generated code for `AddController()` is
```csharp
// Internal
[DllImport(ImportResolver.Library, EntryPoint = "gtk_widget_add_controller")]
public static extern void AddController(IntPtr widget, IntPtr controller);

// Public
public void AddController(Gtk.EventController controller)
{
    Gtk.Internal.Widget.AddController(this.Handle, controller.Handle);   
}
```

[gtk_widget_add_controller](https://docs.gtk.org/gtk4/method.Widget.add_controller.html) says `The instance takes ownership of the data, and is responsible for freeing it`, so it doesn't add a reference but holds onto it and will remove a reference sometime later when the widget is destroyed.
I think the problem is that the original EventController instance may still have an OwnedHandle so it can remove its reference, bringing the refcount to 0, and destroy the native object if the EventController doesn't live as long as the widget?

The attached snippet (modified version of the Adwaita sample) should reproduce it and output many errors like the following when UI events like mouse moves occur
```
(<unknown>:39996): Gtk-CRITICAL **: 23:44:13.325: gtk_event_controller_get_propagation_phase: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed
```

Example:
```csharp
using System;

var application = Adw.Application.New("org.gir.core", Gio.ApplicationFlags.FlagsNone);
application.OnActivate += (sender, args) =>
{
    var window = Gtk.ApplicationWindow.New((Adw.Application) sender);
    window.Title = "Window";
    window.SetDefaultSize(300, 300);

    var c = Gtk.EventControllerKey.New();
    window.AddController(c);

    GLib.Functions.TimeoutAddFull(0, 10, delegate
    {
        GC.Collect();
        GC.WaitForPendingFinalizers();
        return false;
    });

    window.Show();
};
return application.Run();
```

**Comment by badcel** [comment]
Great find! Your explanation sounds totally reasonable to me.

I think there is something missing in case of full  ownership transfer.
