### ISSUE TITLE
Verify handling of string return parameters on Windows

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#791]
Doing some preliminary testing on Windows I noticed some crashes related to methods returning a string, e.g. `GdkPixbuf.Internal.PixbufFormat.GetName()`

On Windows it looks like the default marshalling for string return values expects the string to have been allocated with `CoTaskMemAlloc()`, so there is a mismatch of allocators when it frees the native return value (https://github.com/dotnet/runtime/issues/13140)
I suspect we'll probably just have to do the marshalling manually and free using `g_free()` if there is an ownership transfer to make sure the same allocator is being used.

**Comment by badcel** [comment]
We should add some GirTest code to verify string behavior on all 3 platforms:

- string as return value
- string as in parameter
- String as out parameter
- string as in/out parameter

For those cases we need to check which kind of ownership transfer makes sense and multiply the tests with the number of useful ownership transfers.

Each of the detected use cases must be checked for either UTF8 string and platform string. See https://github.com/gircore/gir.core/blob/main/src/Generation/GirLoader/Output/String.cs

**Comment by cameronwhite** [comment]
For filename strings, I think we should have an `IntPtr` for the internal bindings and use `g_filename_from_utf8` to get a string in the correct encoding.
From https://docs.gtk.org/glib/character-set.html there is some complexity involved in determining which encoding is actually needed (e.g. the `G_FILENAME_ENCODING` environment variable can change this) so using the standard glib method seems like the safe approach.

**Comment by badcel** [comment]
Closed as strings are implemented. String arrays are missing and are handled in #866.
