### ISSUE TITLE
Update WebKit-5.0 to WebKit-6.0

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#799]
As WebKit-5.0 is a development release it should be updated to it's final version 6.0 once it is available in the flatpak SDK (probably with GNOME 44).

See: https://github.com/gircore/gir.core/pull/746#issuecomment-1426868383

**Comment by mcatanzaro** [comment]
It's already available in org.gnome.Platform//master and will indeed be available in org.gnome.Platform//44, yes. (You'll notice because it _replaces_ the -5.0 API.)

**Comment by mcatanzaro** [comment]
> and will indeed be available in org.gnome.Platform//44

Um, and this should appear sometime next week hopefully, because the runtime is branched with the 44.beta release, and the tarball deadline for that was 10 minutes ago.

**Comment by badcel** [comment]
Do you know how long the flatpak runtimes are supported? If the runtime version "43" is supported in parallel to version "44" there must be probably both versions available as nuget packages.

**Comment by mcatanzaro** [comment]
> Do you know how long the flatpak runtimes are supported?

12 months. The 43 runtime (last to ship webkit2gtk-5.0) will go EOL when the 45 runtime is released in September.
