### ISSUE TITLE
Unimplementable methods can be rendered in interfaces

### ISSUE THREAD

**Issue by hol430** [gircore/gir.core#806]
While working on gtksourceview bindings, I've discovered that sometimes methods can be rendered in an interface which cannot be implemented. When this happens, the generated bindings fail to build, because the method in the interface is not implemented anywhere. Missing methods may be a problem, but I thought I'd file this issue as there is a broader issue here -- the method probably shouldn't to be rendered in the interface if it can't be implemented.

When I ran into this it happened because the return type of the method couldn't be converted from an internal to a public type (ie `ReturnTypeToManagedExpression.Render()` was throwing). This check was occurring when the method was being rendered in a class, but not when rendered in an interface.

**Comment by badcel** [comment]
This affects functions without an interface, too. To fix this the public return type renderer and the expression renderer for public return types must support the same feature set.

This means that the fallback parameter must be removed for the public return type renderer and the code should look like the expression renderer.
