### ISSUE TITLE
Release probably blocked

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#810]
Currently it is not possible to make a release without updating the pipeline due to a breaking change in the most recent dotnet 7 release. It should be fixed in a hot fix release automatically.

See: https://github.com/dotnet/sdk/issues/30625

The fix is here: https://github.com/dotnet/sdk/pull/30660

statement regarding hotfix: https://github.com/dotnet/sdk/issues/30624#issuecomment-1435408741

Encountered in [HidApi.Net CI](https://github.com/badcel/HidApi.Net/actions/runs/4207705907)

**Comment by PlatinumLucario** [comment]
The error seems to have downgraded to a warning as of 7.0.201, [as detailed here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid).

**Comment by PlatinumLucario** [comment]
@badcel I'm quite curious, is the issue still present since the hotfix was released and the error being downgraded to a warning?

**Comment by badcel** [comment]
I will do a release in the coming days. We will see, as the projects are configured with "treat warning as error". But somehow this does not affect all warnings. I did not yet tried figure out the difference.

**Comment by badcel** [comment]
The release is out. It worked like a charm :rocket:
