### ISSUE TITLE
Support GTK-3.0

### ISSUE THREAD

**Issue by iahung** [gircore/gir.core#817]
GTK-3.0 is still the most widely used version of GTK.

**Comment by badcel** [comment]
Thanks for your feedback.

We explicitly dropped support for GTK-3.0 with #396 as it is to much of a burden both maintaining wise and from a coding perspective.

But you are not out of luck if you want to write an application using GTK-3.0 you can use https://github.com/GtkSharp/GtkSharp.

If you some time later want to convert to GTK-4.0 you can switch to gir.core. The lower level APIs should be pretty similar as both projects build upon the same API definitions (gir files).
