### ISSUE TITLE
Add support for Gtk.FileDialog and other dialog-related classes introduced in 4.10

### ISSUE THREAD

**Issue by PlatinumLucario** [gircore/gir.core#830]
About a week or two ago, GTK Docs still had FileDialog, FontDialog, AlertDialog and some other dialog-related classes under the 'unstable' label, since they were completely new, now the unstable label has been removed as of GTK library version 4.11.

According to the GTK Docs, FileDialog is the replacement to FileChooserDialog and FileChooserNative when GTK5 is released, and the deprecated classes along with their methods and properties won't exist in GTK5, but like with anything that's deprecated in GTK4, it will always exist in GTK4. By having the bindings for these new classes introduced in 4.10, this will ensure that any GTK4 project is ready to migrate to GTK5 when it's released.

References to the new classes:
https://docs.gtk.org/gtk4/class.FontDialog.html
https://docs.gtk.org/gtk4/error.DialogError.html
https://docs.gtk.org/gtk4/class.ColorDialog.html
https://docs.gtk.org/gtk4/class.AlertDialog.html

References to the deprecated classes:
https://docs.gtk.org/gtk4/class.Dialog.html
https://docs.gtk.org/gtk4/class.FileChooserNative.html
https://docs.gtk.org/gtk4/class.FileChooserDialog.html

It may also be a good idea to check the [GTK repo deprecated folder](https://gitlab.gnome.org/GNOME/gtk/-/tree/main/gtk/deprecated) to and then search in [here](https://docs.gtk.org) for any new APIs added in.

**Comment by cameronwhite** [comment]
I think these will be added automatically after the [GIR introspection files](https://github.com/gircore/gir-files) are updated, once GTK 4.10 packages are available on the CI builds for each platform

**Comment by PlatinumLucario** [comment]
Awesome! In the meantime, I will continue to use FileChooserNative

**Comment by badcel** [comment]
Starting with version [0.5.0-preview.3](https://github.com/gircore/gir.core/releases/tag/0.5.0-preview.3) the Gir files were updated and contain the GTK 4.12 APIs.

Version [0.5.0-preview.4](https://github.com/gircore/gir.core/releases/tag/0.5.0-preview.4) is available, too.

If you miss some more features feel free to open a new issue as the ones requested here are available now.
