### ISSUE TITLE
Create a WidgetCatalog sample

### ISSUE THREAD

**Issue by na2axl** [gircore/gir.core#88]
The WidgetCatalog will showcase the usage of every widgets in GTK3 (WidgetCatalog3) and GTK4 (WidgetCatalog4) with Gir.Core. This kind of sample is the first one experienced developers and newbies search when browsing a new UI framework.

**Comment by badcel** [comment]
Samples are very welcome. More complex samples like this one should probably maintained in a separate repository which references the gircore nuget packages. We can allways add a link to the repository.

The samples in the main repository should fulfill a very specific task to avoid maintainers getting lost in complex code if something must be updated. At the same time simple samples make it easier for new users to get a hint at specific problems.
