### ISSUE TITLE
Generation of global functions

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#91]
Currently all global functions are public. Probably each function has some class where it could part of as a `public static` method.

Do we want to make the global class internal and call the global functions only from inside our library? 

Alternatively we keep the global class `public`. In this case we should probably put the methods into a `protected static Native` class because the method signatures are full of `IntPtr` parameters. Then we could try to generate methods with a user friendly signature to access the native functions.

**Comment by firox263** [comment]
> Alternatively we keep the global class public. In this case we should probably put the methods into a protected static Native class because the method signatures are full of IntPtr parameters. Then we could try to generate methods with a user friendly signature to access the native functions.

I think this is probably the best idea, since that way we don't block access to functions like `Gtk.Init()`, etc, for small tests and people not using `GtkApplication`.

**Comment by badcel** [comment]
Okay, than we do it in this way. This is probably a good idea because we do not change the general structure of the API. We can still use the global functions in our toolkit layer.
