### ISSUE TITLE
BoxedWrapper fails for opaque record types

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#957]
While testing out the 0.5.0-preview.1 release with Pinta, I noticed that `value.GetBoxed(Gdk.FileList.GetGType())` is now throwing an exception.

Adding the following code to the `OpaqueTypedRecordTest` reproduces the same error:
```csharp
    [TestMethod]
    public void SupportsWrapHandle()
    {
        var recordTester = OpaqueTypedRecordTester.New();

        var wrapped = (OpaqueTypedRecordTester) GObject.Internal.BoxedWrapper.WrapHandle(
                handle: recordTester.Handle.DangerousGetHandle(),
                ownsHandle: false,
                gtype: OpaqueTypedRecordTester.GetGType()
        );

        wrapped.Handle.Should().Be(recordTester.Handle);
    }
```

Error message:
```
System.Exception: Type GirTest.OpaqueTypedRecordTester does not define an IntPtr constructor. This could mean improperly defined bindings
```

It looks like the reflection is failing because opaque records no longer have the constructor signature it's looking for?

**Comment by badcel** [comment]
Thank you for the report. This should be kept in mind for all kinds of boxed records (opaque / not opaque)
