### ISSUE TITLE
Unable to load DLL 'GstVideo' or one of its dependencies

### ISSUE THREAD

**Issue by vhytyk** [gircore/gir.core#969]
Hi,
I'm trying to play a video from my RaspberyPI on Windows .net 6 WinForms app.
It's working ok with Pipeline playing in separate window (using Gir.Core.Gst package). What I want to do is to play it inside WinForms.Panel.
For that I'd need GstVideo classes I beleive. But when I try to add Gir.Core.GstVideo and use one of it's classes, in particular GstVideo.Functions.IsVideoOverlayPrepareWindowHandleMessage(), I got an error:
`System.DllNotFoundException: 'Unable to load DLL 'GstVideo' or one of its dependencies: The specified module could not be found.`

What I do wrong?

**Comment by vhytyk** [comment]
Ok, I resolved this one by GstVideo.Module.Init().
But I still don't get how could I set proper window handle here:
```
...
private void Bus_OnSyncMessage(Gst.Bus sender, Gst.Bus.SyncMessageSignalArgs args)
{
    if (GstVideo.Functions.IsVideoOverlayPrepareWindowHandleMessage(args.Message))
    {
        args.Message.Handle.
        GstVideo.VideoOverlay overlay; //what should I create here? 
        overlay.SetWindowHandle(myWindowPtr) 
    }
}
...
```

**Comment by badcel** [comment]
Hi,

I think your question can be answered if you refer to the following issues: #964 #966

In short: this currently does not work out of the box. You need to dig into the `internal` namespace and potentially need to do some manual bindings.

Any help on improving the generator is welcome.
